const restaurants=[{
    "name": "Yorker",
    "city": "Oklahoma City",
    "state": "Oklahoma",
    "phone_number": "405-769-4914",
    "genre": "Sci-Fi"
  }, {
    "name": "Bradly",
    "city": "Omaha",
    "state": "Nebraska",
    "phone_number": "402-818-1947",
    "genre": "Comedy"
  }, {
    "name": "Had",
    "city": "Fort Wayne",
    "state": "Indiana",
    "phone_number": "260-690-3194",
    "genre": "Adventure|Drama|Romance"
  }, {
    "name": "Kirstyn",
    "city": "Tyler",
    "state": "Texas",
    "phone_number": "903-513-0678",
    "genre": "Horror"
  }, {
    "name": "Cody",
    "city": "New Haven",
    "state": "Connecticut",
    "phone_number": "203-130-5561",
    "genre": "Action|Animation|Children|Comedy|Musical"
  }, {
    "name": "Ebonee",
    "city": "Bronx",
    "state": "New York",
    "phone_number": "347-298-2520",
    "genre": "Drama"
  }, {
    "name": "Xena",
    "city": "Saint Cloud",
    "state": "Minnesota",
    "phone_number": "320-135-9785",
    "genre": "Comedy"
  }, {
    "name": "Ellen",
    "city": "Columbus",
    "state": "Ohio",
    "phone_number": "740-319-1169",
    "genre": "Comedy|Horror"
  }, {
    "name": "Mara",
    "city": "Albany",
    "state": "New York",
    "phone_number": "518-717-5512",
    "genre": "Drama"
  }, {
    "name": "Cate",
    "city": "Austin",
    "state": "Texas",
    "phone_number": "512-601-2931",
    "genre": "Documentary"
  }, {
    "name": "Lin",
    "city": "New Orleans",
    "state": "Louisiana",
    "phone_number": "504-819-0389",
    "genre": "Horror|Thriller"
  }, {
    "name": "Kerrill",
    "city": "El Paso",
    "state": "Texas",
    "phone_number": "915-798-0209",
    "genre": "Drama|Fantasy"
  }, {
    "name": "Thorin",
    "city": "Los Angeles",
    "state": "California",
    "phone_number": "310-379-7574",
    "genre": "Action|Thriller"
  }, {
    "name": "Bartlett",
    "city": "Honolulu",
    "state": "Hawaii",
    "phone_number": "808-341-8645",
    "genre": "Comedy|Crime|Mystery"
  }, {
    "name": "Aleece",
    "city": "Washington",
    "state": "District of Columbia",
    "phone_number": "202-189-1010",
    "genre": "(no genres listed)"
  }, {
    "name": "Anastasie",
    "city": "Kent",
    "state": "Washington",
    "phone_number": "206-912-0341",
    "genre": "Comedy|Romance"
  }, {
    "name": "Harwell",
    "city": "Boston",
    "state": "Massachusetts",
    "phone_number": "617-977-9100",
    "genre": "Comedy|Fantasy|Horror"
  }, {
    "name": "Codi",
    "city": "Atlanta",
    "state": "Georgia",
    "phone_number": "404-557-6419",
    "genre": "Horror|Sci-Fi"
  }, {
    "name": "Evelina",
    "city": "Mesquite",
    "state": "Texas",
    "phone_number": "972-328-8097",
    "genre": "Comedy|War"
  }, {
    "name": "Alden",
    "city": "San Jose",
    "state": "California",
    "phone_number": "408-775-3635",
    "genre": "Animation|Sci-Fi"
  }, {
    "name": "Emmanuel",
    "city": "Montgomery",
    "state": "Alabama",
    "phone_number": "334-976-0524",
    "genre": "Drama|Horror|Musical"
  }, {
    "name": "Caron",
    "city": "Dallas",
    "state": "Texas",
    "phone_number": "469-779-3414",
    "genre": "Drama"
  }, {
    "name": "Rolando",
    "city": "Orlando",
    "state": "Florida",
    "phone_number": "407-368-8179",
    "genre": "Action|Comedy|Crime|Drama|Thriller"
  }, {
    "name": "Nada",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "phone_number": "215-866-2223",
    "genre": "Drama"
  }, {
    "name": "Nye",
    "city": "Tyler",
    "state": "Texas",
    "phone_number": "903-476-9854",
    "genre": "Crime|Drama|Thriller"
  }, {
    "name": "Jeana",
    "city": "Los Angeles",
    "state": "California",
    "phone_number": "213-481-0719",
    "genre": "Comedy"
  }, {
    "name": "Bobbie",
    "city": "Savannah",
    "state": "Georgia",
    "phone_number": "912-783-2670",
    "genre": "Horror|Sci-Fi"
  }, {
    "name": "Jordan",
    "city": "Woburn",
    "state": "Massachusetts",
    "phone_number": "339-293-3852",
    "genre": "Horror|Mystery|Thriller"
  }, {
    "name": "Pacorro",
    "city": "Seminole",
    "state": "Florida",
    "phone_number": "941-337-3017",
    "genre": "Drama"
  }, {
    "name": "Margeaux",
    "city": "Hagerstown",
    "state": "Maryland",
    "phone_number": "240-213-2454",
    "genre": "Crime|Mystery|Thriller"
  }, {
    "name": "Kinsley",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "phone_number": "215-402-0747",
    "genre": "Comedy"
  }, {
    "name": "Hermy",
    "city": "Saint Louis",
    "state": "Missouri",
    "phone_number": "314-896-4057",
    "genre": "Drama|Fantasy|Romance"
  }, {
    "name": "Rochette",
    "city": "High Point",
    "state": "North Carolina",
    "phone_number": "336-300-6017",
    "genre": "Crime|Drama"
  }, {
    "name": "Rodrigo",
    "city": "Spokane",
    "state": "Washington",
    "phone_number": "509-146-3596",
    "genre": "Documentary"
  }, {
    "name": "Bayard",
    "city": "Lincoln",
    "state": "Nebraska",
    "phone_number": "402-617-9786",
    "genre": "Thriller"
  }, {
    "name": "Anderson",
    "city": "Shawnee Mission",
    "state": "Kansas",
    "phone_number": "913-592-0839",
    "genre": "Comedy|Romance"
  }, {
    "name": "Fanny",
    "city": "Washington",
    "state": "District of Columbia",
    "phone_number": "202-231-8753",
    "genre": "Children|Comedy"
  }, {
    "name": "Christoffer",
    "city": "New York City",
    "state": "New York",
    "phone_number": "212-587-5021",
    "genre": "Action|Sci-Fi|Thriller"
  }, {
    "name": "Bella",
    "city": "Naperville",
    "state": "Illinois",
    "phone_number": "630-416-5572",
    "genre": "Action|Adventure|Animation"
  }, {
    "name": "Kiley",
    "city": "Minneapolis",
    "state": "Minnesota",
    "phone_number": "612-959-7008",
    "genre": "Documentary"
  }, {
    "name": "Korry",
    "city": "New Haven",
    "state": "Connecticut",
    "phone_number": "203-441-8858",
    "genre": "Action|Comedy|Horror|Thriller"
  }, {
    "name": "Leena",
    "city": "Shawnee Mission",
    "state": "Kansas",
    "phone_number": "913-428-2885",
    "genre": "Action|Adventure"
  }, {
    "name": "Dorolisa",
    "city": "Charlotte",
    "state": "North Carolina",
    "phone_number": "704-750-8024",
    "genre": "Drama|Mystery"
  }, {
    "name": "Willie",
    "city": "Orlando",
    "state": "Florida",
    "phone_number": "407-922-4363",
    "genre": "Drama|War"
  }, {
    "name": "Rasla",
    "city": "Memphis",
    "state": "Tennessee",
    "phone_number": "901-515-0745",
    "genre": "Comedy|Romance"
  }, {
    "name": "Carlie",
    "city": "Champaign",
    "state": "Illinois",
    "phone_number": "217-641-9367",
    "genre": "Drama|War"
  }, {
    "name": "Maxwell",
    "city": "Madison",
    "state": "Wisconsin",
    "phone_number": "608-287-3022",
    "genre": "Drama"
  }, {
    "name": "Rudie",
    "city": "Roanoke",
    "state": "Virginia",
    "phone_number": "540-266-2829",
    "genre": "Comedy|Drama|Romance"
  }, {
    "name": "Rachelle",
    "city": "Springfield",
    "state": "Illinois",
    "phone_number": "217-675-2133",
    "genre": "Action|Adventure|Drama"
  }, {
    "name": "Jocelyne",
    "city": "Albuquerque",
    "state": "New Mexico",
    "phone_number": "505-683-3842",
    "genre": "Drama|Romance"
  }]
  module.exports = restaurants